;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Content/Localization/Game
DestinationPath=Content/Localization/Game
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=ko
CulturesToGenerate=ru
CulturesToGenerate=ja
CulturesToGenerate=zh-Hans
CulturesToGenerate=zh-Hant
CulturesToGenerate=fr
CulturesToGenerate=it
CulturesToGenerate=de
CulturesToGenerate=es-ES
CulturesToGenerate=pt-BR
CulturesToGenerate=pl
CulturesToGenerate=tr
CulturesToGenerate=uk
ManifestName=Game.manifest
ArchiveName=Game.archive
PortableObjectName=Game.po

[GatherTextStep0]
CommandletClass=InternationalizationExport
bImportLoc=true
LocalizedTextCollapseMode=ELocalizedTextCollapseMode::IdenticalTextIdAndSource
POFormat=EPortableObjectFormat::Unreal

